### ISSUE TITLE
Could not set unknown property 'kotlin_version' for object of type org.gradle.api.internal.initialization.DefaultScriptHandler.

### ISSUE THREAD

**Issue by leonardltk** [VoiceGym/voicegym#35]
Error 1 : 
```
1: Task failed with an exception.
-----------
* Where:
Build file 'C:\...\voicegym\app\build.gradle' line: 3

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not initialize class org.jetbrains.kotlin.gradle.internal.KotlinSourceSetProviderImplKt
```
following [this advice](https://stackoverflow.com/questions/60833542/kotlin-gradle-could-not-initialize-class-class-org-jetbrains-kotlin-gradle-inter), i added these to `build.gradle (Project: voicegym)`
```
buildscript {
    ext.kotlinVersion = '1.3.72' // previously  '1.2.60'
    ext.springBootVersion = '2.0.4.RELEASE'
    ext.anko_version='0.10.4'
    repositories {
        ...
        mavenCentral()
    }
    dependencies {
        ...
    }
}

```

Now i am stuck with this error
```
Build file 'C:\...\voicegym\build.gradle' line: 5

A problem occurred evaluating root project 'voicegym'.
> Could not get unknown property 'kotlin_version' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Comment by leonardltk** [comment]
i just needed to change `ext.kotlinVersion = ...` to `ext.kotlin_version = ...`

**Comment by pektinasen** [comment]
The last time we tried to build this project was 2 years ago.
If you tried to update dependencies/androidVersions/kotlinVersions/gradleVersions, I'm sure there will be some problems.
We both have kind of moved on from android developement. But if you submit a working PR to build it again, I'm happy to merge it.
I'm also happy to answer specific questions you might have about the project.
