### ISSUE TITLE
Unresolved reference: CommonPool

### ISSUE THREAD

**Issue by leonardltk** [VoiceGym/voicegym#36]
For these files : `App.kt` `RecordingListViewModel.kt` `RecordActivity.kt`

There is this error:
```
Unresolved reference: CommonPool
```

**Comment by leonardltk** [comment]
There is a need to replace the following
```java
import kotlinx.coroutines.CommonPool
import kotlinx.coroutines.launch
```
with
```java
import kotlinx.coroutines.experimental.*
```

**Comment by pektinasen** [comment]
I would assume this is due to your change of kotlin versions, as coroutines where not experimental anymore in 1.3+.
As with #35: happy to merge a PR.

**Comment by KayleeTheMech** [comment]
@leonardltk i updated some dependencies to more current versions. You now longer should have this issue.
