### ISSUE TITLE
Project no longer on the PlayStore - current .akp for download?

### ISSUE THREAD

**Issue by menelic** [VoiceGym/voicegym#45]
Hi, this is a great project showcasing how software solutions informed by specific trans perspectives and needs benefit literally everyone with a voice they want to train. Unfortunately it seems that it is no longer available on google play? I could not find it on F-Droid either. My interest would be to use it in voice and singing training and provide feedback here based on that. I believe both the use case and possible insights into UX and display needs could benefit every other use case as well. As there has been recent activity in this repo here is hoping that development will continue - pls share a link to a current .akp or re-publish on google play and/or F-Droid

**Comment by KayleeTheMech** [comment]
Hi, I hope your expectations are not too high! It's mostly just a spectrogram display right now. I'm currently trying to get it republished; sorry don't have a lot of time for google's bs right now. If I ever start voice training again I might just start to work on the project again. Contributions are very welcome! I have two items on my todo list
- [ ] write a proper readme how to contribute or start development of the project
- [ ] add a publishing pipeline to the CI/CD build

**Comment by KayleeTheMech** [comment]
It's back on the playstore! 

https://play.google.com/store/apps/details?id=de.voicegym.voicegym
