### ISSUE TITLE
Migration of the source code from GitHub to Codeberg?

### ISSUE THREAD

**Issue by linux-lukas** [VoiceGym/voicegym#50]
Has it ever been possible to break away from the dependency on GitHub (owned by Microsoft) and migrate the source code to Codeberg.org?

**Comment by KayleeTheMech** [comment]
Hey Lukas2112.

I'm definitely not going to use any code repository platform that doesn't provide CI/CD runners. 
I'm also going to avoid spending my free-time learning something I'm not particularly invested or interested in and that isn't useful for my ability to earn money.

Sorry.

**Comment by linux-lukas** [comment]
Codeberg (meanwhile) offers CI/CD Runner. 

See: https://ci.codeberg.org/
